### PR TITLE
[T-6395][13.0][MIG]account_financial_report_block_pdf: Migration to 13.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard Migration
T-6395

@HaraldPanten 
@ValentinVinagre

### CODE REVIEW

**Review by Tisho99 — CHANGES_REQUESTED** [review]
The commit history is not okay, can you fix it?

There should be 6 commits. The 4 of the 17.0 branch, the pre-commit auto fixes, and the migration

**Review by Tisho99 — APPROVED** [review]
LGTM

**Comment by Tisho99** [comment]
@RogerSans recuerda poner en el nombre del  PR el ID de la tarea

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Pull request merged**
