### PR TITLE
[15.0][MIG] hide_invoice_shipping_address: Migration to 15.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6202

@HaraldPanten 
@ValentinVinagre 
@luis-ron

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@Tisho99 Can you review this?

**Review by Tisho99 — CHANGES_REQUESTED** [review]
@RogerSans 

Why the commit history is not migrated? We should act in a similar way to OCA

Can you migrate it? Or there is a reason not to it?

**Review by Tisho99 — APPROVED** [review]
LGTM Code Review

**Comment by RogerSans** [comment]
@manuel-florido Can be merged?

**Comment by ValentinVinagre** [comment]
@RogerSans @Tisho99 why have changes been uploaded in 2 different modules in the same PR without indication?
account_financial_report_block_pdf
hide_invoice_shipping_address

**Comment by RogerSans** [comment]
@ValentinVinagre i don't remember the reason, sorry. i keep in mind for another time to separate in two PR.

**Pull request merged**
